### ISSUE TITLE
strong default for metalnx.enable.dashboard=false

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#103]
When upgrading from pre-2.0.0, the `irods/metalnx:2.0.0` release is very angry if `metalnx.enable.dashboard` is not defined.

Metalnx should still run, even if the following isn't defined in `metalnx.properties`:
```
# show dashboard (off by default due to performance issues)
metalnx.enable.dashboard=false
```

**Comment by michael-conway** [comment]
I'd address this through docu
