### ISSUE TITLE
group names aren't unique in federation

### ISSUE THREAD

**Issue by bh9** [irods-contrib/metalnx-web#111]
The groups table assumes names are unique, without including the zone name in them. This is not necessarily the case when running in federated zones, as groups can have the same name, but belong to different zones, therefore making them different groups. This causes the constraint at https://github.com/irods-contrib/metalnx-web/blob/ba9e5cdd88c871a4d151ee742a433c4b7628e255/src/metalnx-tools/src/main/resources/migrations/V1__Base_version.sql#L600-L601 to fail, meaning that the groups table is never completed.
The sql command which it fails on is 
```
Hibernate: 
    insert 
    into
        groups
        (additional_info, data_grid_id, groupname) 
    values
        (?, ?, ?)
2019-08-05 10:36:58 WARN  SqlExceptionHelper:143 - SQL Error: 0, SQLState: 23505
2019-08-05 10:36:58 ERROR SqlExceptionHelper:144 - ERROR: duplicate key value violates unique constraint "groups_groupname_key"
Detail: Key (groupname)=(ss_2520) already exists.
2019-08-05 10:36:58 ERROR SyncJobs:212 - Could not synchronize database and iRODS (Groups): 
org.hibernate.exception.ConstraintViolationException: ERROR: duplicate key value violates unique constraint "groups_groupname_key"
  Detail: Key (groupname)=(ss_2520) already exists.
```
because we have 2 groups called ss_2520 (or more accurately ss_2520#Sanger1 and ss_2520#seq)
```
irods@irods-sanger1:~$ iadmin lgd ss_2520
user_id: 61718
user_name: ss_2520
user_type_name: rodsgroup
zone_name: Sanger1
user_info: 
r_comment: 
create_ts 2013-02-20.09:46:22
modify_ts 2013-02-20.09:46:22
user_id: 61721
user_name: ss_2520
user_type_name: rodsgroup
zone_name: seq
user_info: 
r_comment: 
create_ts 2013-02-20.09:58:29
modify_ts 2013-02-20.09:58:29
```

**Comment by michael-conway** [comment]
How do folks feel about just drawing down some of the group/user database overhead and return to going direct against iRODS? If there is any add'l info perhaps it needs to be AVU data so that things like federation are smoother.

**Comment by michael-conway** [comment]
P.S. we had some of our own needs to update and simplify the group admin functions soon

**Comment by trel** [comment]
I'd be very happy to eventually get rid of the metalnx local database.   Yes, if we can query for user/groups directly against the server, it means the client can't be 'stale' or wrong in any way - and of course, will make deployment much easier.

**Comment by michael-conway** [comment]
That's what I'm proposing, as a gradual drawdown...I agree that starting
with user/groups is needed, we ran into our own issues with group names and
have a need so simplify group management (including as a groupadmin) and
permission setting, it was on our own boards.

The federation capabilities are hindered by reliance on a database since
the databases are not federated. It does make sense for things like
favorites and bookmarks if you take the perspective of having a 'home'
zone, so you can favorite files and collections where you don't have write
access, etc for an AVU or across a federation...

So if retracting on groups and users via the metalnx database doesn't break
any needed functionality, I think this is the solution for the original
issue.

**Comment by PeteClapham** [comment]
Hello guys,
is this an update that is likely to make it onto a roadmap and if so what sort of timeframe might it arrive? Sorry to ask, but we are actively looking for a web based cross federation interface for our local customers.

Thanks for your help
Pete

**Comment by michael-conway** [comment]
Hi Pete I'll jump on this one then. I've found the groups database an
irritant here anyhow. Let's shoot for 2 weeks out for a version to test.
I'll take an afternoon this weekend.

Sound good?

**Comment by PeteClapham** [comment]
Hi Mike,

That sounds great, many thanks for getting on this so quickly. Ideally I’m hoping that the excellent Metalnx base will become a standard our teams can adopt locally.

Regards
Pete

**Comment by michael-conway** [comment]
...work in progress...update...

* yanked DataGridUserGroup and related DAOs, entities this is peppered through the services
* currently recasting GroupService to delegate group calls directly to iRODS, sorting out how zones play in, allowing access to groups across federated zones
* yanked currently unused GroupBookmarks DAOs and entities to be revisited later

These should fit in relatively neatly under the  existing group stuff in the interface. The list all is dumb, eventually a better way of filtering the group list but that won't be in this round

**Comment by michael-conway** [comment]
WIP first cut at service changes done...integrating into controller/view level now...Have yanked User Profile functionality for the moment, since that relies on groups in the dbase as well.

**Comment by michael-conway** [comment]
for @bh9 and @trel. Sorry this took a bit longer as I pulled on a few threads. Status is that its -working- in the sense that group/group bookmark/user profile are no longer a thing in the database, and the user can have non-unique user names in diff zones. I think this is actually very close. 

What is left is to think through how represent intent. That is, where we're searching for users in a different zone to bring over as a group on the home zone, and other such semantics. This is not as bad as it sounds. But perhaps @trel if we sat in a screen share and talked through this in a systematic fashion? We could do that this week or early next. A bit of a run-through and what I'm concerned with should make sense!

**Comment by trel** [comment]
tomorrow noonish should work.  i'll send an invite.

**Comment by michael-conway** [comment]
Testing is done, a few visual cleanups to do. This will all be merged into the master branch tomorrow and we can try a build from there.

**Comment by trel** [comment]
awesome.

**Comment by PeteClapham** [comment]
Fantastic news, thanks guys. Will test when available
Pete

**Comment by michael-conway** [comment]
merged into master...closing this, will pick up cleanups and testing as separate sub-issues

**Comment by trel** [comment]
These are included in master - closing.
