### ISSUE TITLE
Add pluggable search framework

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#113]
Add 'google like' search features to Metalnx. See 
https://github.com/DICE-UNC/jargon-irods-ext/issues/10

For details.

This adds the ability to plug in indexes to provide standard free text, free text with attribute flags, or attribute 'builder' type queries that return results in a 'google result' or a standard virtual collection type listing.

This feature would allow site-specific index schema to be managed and plugged into metalnx or other interfaces by configuring one or multiple endpoints. The actual search support will be implemented by implementing a microservice that conforms to a standard swagger api. 

The search feature can be enabled or disabled.

There is a future potential to create a standard indexing and search of the iRODS catalog for standard file/collection system and AVU metadata.

**Comment by michael-conway** [comment]
Cross reference of related issues and branches of supporting libraries:

* Current location of Swagger API (work in progress): https://app.swaggerhub.com/apis/michael-conway/data-grid-search-api/1.0.0-oas3

* Jargon-extensions-if to hold new supporting interfaces, swagger data model for search api clients - https://github.com/DICE-UNC/jargon-extensions-if/issues/30, branch: https://github.com/DICE-UNC/jargon-extensions-if/tree/30-indexing

* Jargon-irods-ext implementations of interfaces - https://github.com/DICE-UNC/jargon-irods-ext/issues/10, branch: https://github.com/DICE-UNC/jargon-irods-ext/tree/10-indexing


This is taking place in the metalnx development branch

**Comment by michael-conway** [comment]
PS Here's our current test Swagger implementation that can serve as a model...

https://github.com/michael-conway/grid-search-service

**Comment by trel** [comment]
This merge commit (https://github.com/irods-contrib/metalnx-web/commit/04082e673f6e2f40d8c959319508cc059f1b65e7) pulled a large chunk of the dev branch into master this morning.

**Comment by michael-conway** [comment]
Let's close this feature development and track any bugs in new issues.
