### ISSUE TITLE
change display when no files in a user folder

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#125]
![image](https://user-images.githubusercontent.com/1097261/69266199-b8b49b80-0b98-11ea-820d-12c89435b612.png)

**Comment by deeppatelcs** [comment]
![Screen Shot 2019-11-21 at 1 21 35 PM](https://user-images.githubusercontent.com/28636342/69365229-dd287a80-0c61-11ea-9833-3de889b3dc94.png)
