### ISSUE TITLE
Attempting to "view info" on a dataObject fails in 4.1.12

### ISSUE THREAD

**Issue by bh9** [irods-contrib/metalnx-web#134]
More for awareness, in case anyone else hits this than asking for a fix, since we're hoping to move from 4.1.X soon:
Attempting to use the "View Info" option results in a 500 error, because metalnx attempts to collect DATA_RESC_ID which isn't populated until 4.2.X, so irods gives -823000 (CAT_UNKNOWN_TABLE)

**Comment by michael-conway** [comment]
see for testing https://github.com/alanking/irods_docker/tree/4.1.13/4-1

**Comment by michael-conway** [comment]
see branch https://github.com/irods-contrib/metalnx-web/tree/134-resc-id

**Comment by michael-conway** [comment]
integrated docker standup into jargon at https://github.com/DICE-UNC/jargon/issues/354

**Comment by michael-conway** [comment]
update...replicated this with the docker harness in the jargon unit tests. @trel @bh9 

Should have this fixed in the AM. Added the docker harness into jargon and will keep 4.1 and add other versions. This would allow much easier bootstrapping of unit tests. We can consider this same rig for python.

**Comment by michael-conway** [comment]
tested at Jargon level...need to update the docker to put up the metalnx database for further testing against 4.1 compose rig and then create a current version compose rig...

**Comment by michael-conway** [comment]
PS that Jargon version was pushed so metalnx can be rebuilt and tested on-site

**Comment by trel** [comment]
closing this as part of 2.1.0.    will revisit after release if necessary.
