### ISSUE TITLE
Dashboard enabled, RMD deployed, but 404 not found

### ISSUE THREAD

**Issue by bzizou** [irods-contrib/metalnx-web#144]
I just installed Metalnx with `metalnx.enable.dashboard=true` and deployed RMD on my servers, but when I get to the dashboard page, I have a `404 - Page Not Found`.
Everything else is working fine, and I can even see the RMD status on the `/metalnx/resources/servers/` page (servers may be green or yellow, and the RMD version is displayed when I click on a server name link).
I'm using irods 4.2.8 with PAM auth.

**Comment by bzizou** [comment]
Could this issue be considered? There's a similar report on the metalnx-rmd repository, pending since january: irods-contrib/metalnx-rmd/issues/4

**Comment by kalylian** [comment]
Hi,

I'm facing the same issue, I think. At least, I have the same behaviour (I can see the metalnx RMD version in the resources page but I'm facing a 404 when clicking on the server name-or the dashboard itself) I've done some digging and this is what I found.

The RMD on each server seems to be contaced. The rmd.log has entries like this:
172.17.0.2 - - [13/Oct/2021 15:48:58] "GET / HTTP/1.1" 200 -
I think that means RMD is working as intended.

The docker log gives me this error message:
2021-10-13 13:51:01 WARN  PageNotFound:1176 - No mapping found for HTTP request with URI [/metalnx/dashboard/] in DispatcherServlet with name 'mvc-dispatcher'
2021-10-13 13:51:01 ERROR HttpErrorController:34 - 404 - Page not found

I think this means I'm missing a mvc mapping. I'm not sure where and what, though. I'm using the default metalnxConfig.xml file (
[link](https://github.com/irods-contrib/metalnx-web/blob/master/docker-test-framework/etc/irods-ext/metalnxConfig.xml)) and the latest commit of both metalnx and RMD.

Any ideas?

Kind regards,

Gudrun

**Comment by trel** [comment]
Additional context can be found in the roadmap
 - https://github.com/irods-contrib/metalnx-web/blob/master/roadmap.md
