### ISSUE TITLE
"iRODS not responding" to a docker-compose deploy of Metalnx

### ISSUE THREAD

**Issue by BlakeGFitch** [irods-contrib/metalnx-web#156]
I am having trouble getting a docker-compose deployed metalnx to work with a local vanilla irods installation on the host xnat00.kyb.local. A screenshot is attached with further information.

In the screen shot, you can see the metalnx docker container has contact with the irods server via the python irods library in the terminal to the right. Below that, you can see the top of the /etc/irods-ext/metalnx.properties in the container. On the left side of the screen shot, you can see the metalnx web interface reporting "iRODS not responding.

Any help in debugging this would be most appreciated! I'm very excited to deploy Metalnx in our organization.

![Screen Shot 20200812](https://user-images.githubusercontent.com/8333093/90017419-ccb2a700-dcab-11ea-8e28-c6b0129266b9.jpeg)

**Comment by michael-conway** [comment]
At first blush this may well be CS_NEG_DONT_CARE. try CS_NEG_REFUSE. It may
well be that it's having a problem trying to establish an SSL
connnection between metalnx and irods.

Try and and eliminate that possibility first, there is a way to add an SSL
cert to the docker image to connect to iRODS if need be.

**Comment by BlakeGFitch** [comment]
That did it! Thank you for the quick response.

**Comment by michael-conway** [comment]
no problem. Note in the docker container you can mount an ssl public key if
you have an irods self-signed cert as a volume and it will be added to the
environment.
