### ISSUE TITLE
URL rewrite on failed auth

### ISSUE THREAD

**Issue by kript** [irods-contrib/metalnx-web#162]
When a user fails to autneticate with PAM, they are redirected to something like `/metalnx/login/exception` which also has a login page. If the user sucessfully authenticates on this page however, the are not redirected to `/metalnx/collections?etcetcetc` but stay on `/metalnx/login/exception`  which gives the appearance of a failed login. However if the user changes the url to be just `/metanx` then they see thier default page/home area.

The failed login should not rewrite the URL permanently and/or a successful login should rewrite correctly.

**Comment by michael-conway** [comment]
This is a little bit messy the way we did it so I am going to try an interim patch that checks if this is submitted when logged in already and reroute to the home page. Not perfect but this will be eventually ripped out anyhow.
