### ISSUE TITLE
Unable to download more than 100MB file

### ISSUE THREAD

**Issue by kript** [irods-contrib/metalnx-web#163]
Despite #143 being resolved, I find that even with `metalnx.download.limit=5120` set in `metalnx.properties` the UI still blocks downloads of larger than 100MB.

**Comment by michael-conway** [comment]
I'm seeing it here...will fold into issues I'm looking at today

**Comment by michael-conway** [comment]
can we check the version? I was able to test a fail with 100 set and then success when I pushed to 6000 in that property...

![image](https://user-images.githubusercontent.com/1097261/95230454-eb2aaf80-07cf-11eb-9c04-9caf5c1a92bc.png)

**Comment by michael-conway** [comment]
...in the about tab by the user dropdown on the upper right

**Comment by michael-conway** [comment]
ps for my own testing I had this in metalnx.properties...

metalnx.download.limit=6000

**Comment by michael-conway** [comment]
Just did upload/download of 3GB no prob...

![image](https://user-images.githubusercontent.com/1097261/95247765-46ff3380-07e4-11eb-970f-0b065e89047a.png)

**Comment by kript** [comment]
> can we check the version? I was able to test a fail with 100 set and then success when I pushed to 6000 in that property...
> 
> ![image](https://user-images.githubusercontent.com/1097261/95230454-eb2aaf80-07cf-11eb-9c04-9caf5c1a92bc.png)

huh, apparently we have `2.1.0-RELEASE` however we built the docker container from `20311a55e66a091f078cd85f1ddc2ad9bdb4ca53`  which might obfuscate the above tag? we'll look into getting the latest.

**Comment by michael-conway** [comment]
Hey John I think that there are a few issues together fixed that might
warrant pushing a test container outright. I can throw one up on
dockerhub if that helps.

**Comment by kript** [comment]
Thanks Mike, worth a try, or we can build from a commit you recommend?

**Comment by michael-conway** [comment]
I can just throw something up on my dockerhub if you'd like...

**Comment by kript** [comment]
Is building from master recommended, or is there a particular commit?



On 8 October 2020 at 13:59:34, Mike Conway (notifications@github.com) wrote:

I can just throw something up on my dockerhub if you'd like...

**Comment by michael-conway** [comment]
Master. I'll push something out to dockerhub tonight, give me a few minutes
and I'll do so!

**Comment by michael-conway** [comment]
michaelconway/metalnx:latest is the latest push. I'm looking into possible
truncation when it gets > 6gb and the file size display now btw.
