### ISSUE TITLE
check file size display for large >5g files and downloaded file sizes

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#166]
check for rendering of file size display and download potentially truncated for large size files.

**Comment by deeppatelcs** [comment]
check #130

**Comment by d-w-moore** [comment]
I built and tested on [tip of master](https://github.com/irods-contrib/metalnx-web/tree/35f00418aeca4633019c70a87a2de46dfff8c9a5) .
I was able to upload arbitrarily large files, but downloads are still clipped at 4.7GB .  The size of the downloaded file always seems to be the true object size and'ed with the bit mask 0xFFFFFFFF, so... it would seem to be an 32-bit integer representation issue.

**Comment by michael-conway** [comment]
Ok will dig.

**Comment by d-w-moore** [comment]
I'm  thinking this may be an (Integer /int) where a (Long / long) should have been used, and probably in the metalnx code itself , as opposed to in the jargon code ... @michael-conway see if your intuition agrees. Thanks!

**Comment by trel** [comment]
bug is over in https://github.com/DICE-UNC/jargon-irods-ext/issues/20

we've demonstrated a fix - will close this when https://github.com/DICE-UNC/jargon-irods-ext/issues/20 is closed.
