### ISSUE TITLE
log is very verbose when syncing user database

### ISSUE THREAD

**Issue by kript** [irods-contrib/metalnx-web#171]
I think this is already being/been addressed, but I can't see it in the list so I thought I'd add it in case it can be fixed/tweaked in time for #167 .

Basically, every time the system sync users from the Zone (and we have hundreds) it logs a few lines for every user - this is leading to logs that are GB in size every day as the sync happens very often (1/min?). I'd like the option to turn this logging down or off, please.

**Comment by trel** [comment]
This was addressed in https://github.com/irods-contrib/metalnx-web/commit/1a29748b0227d109ca3110711a704d2800898ba6

Bumped from every 15s to every 25min.

**Comment by trel** [comment]
We won't add a new configuration option.

This syncing will go away completely once the local database is removed.
