### ISSUE TITLE
SQL error when using iRODS with MySQL database

### ISSUE THREAD

**Issue by ingridbr** [irods-contrib/metalnx-web#174]
Hi,

we are sseing on our irods logs SQL errors that are triggered when users connect to metalnx or navigate it.
The error is:

```Nov 12 15:43:10 pid:77803 NOTICE: cllExecSqlWithResult: SQLExecDirect error: -1, sql:SELECT R_USER_MAIN.user_name, R_USER_MAIN.user_id, R_OBJT_ACCESS.access_type_id, R_USER_MAIN.user_type_name, R_USER_MAIN.zone_name, R_COLL_MAIN.coll_name, USER_GROUP_MAIN.user_name, R_COLL_MAIN.coll_name FROM R_USER_MAIN AS USER_GROUP_MAIN JOIN R_USER_GROUP JOIN R_USER_MAIN ON R_USER_GROUP.user_id = R_USER_MAIN.user_id ON USER_GROUP_MAIN.user_id = R_USER_GROUP.group_user_id JOIN R_OBJT_ACCESS ON R_USER_GROUP.group_user_id = R_OBJT_ACCESS.user_id JOIN R_COLL_MAIN ON R_OBJT_ACCESS.object_id = R_COLL_MAIN.coll_id WHERE R_COLL_MAIN.coll_name = ? AND R_USER_MAIN.user_name = ? ORDER BY R_COLL_MAIN.coll_name, R_USER_MAIN.user_name, R_OBJT_ACCESS.access_type_id DESC
Nov 12 15:43:10 pid:77803 NOTICE: SQLSTATE: 37000
Nov 12 15:43:10 pid:77803 NOTICE: SQLCODE: 1064
Nov 12 15:43:10 pid:77803 NOTICE: SQL Error message: [MySQL][ODBC 5.2(w) Driver][mysqld-5.7.21-log]You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON USER_GROUP_MAIN.user_id = R_USER_GROUP.group_user_id JOIN R_OBJT_ACCESS ON R_' at line 1
Nov 12 15:43:10 pid:77803 NOTICE: chlSpecificQuery cmlGetFirstRowFromSql failure -806000
Nov 12 15:43:10 pid:77803 NOTICE: _rsSpecificQuery: specificQuery status = -806000
Nov 12 15:43:10 pid:77803 NOTICE: rsSpecificQuery: rcSpecificQuery failed, status = -806000
```

I have found that a similar error was reported long ago for an Oracle Database (https://github.com/irods-contrib/metalnx-web/issues/5)  but the issue was closed and I assume fixed. 

Metalnx seems still to work properly except for a problem with the search that seems the same as the one referred on: #135 

The details of our installation:

metalnx version: master branch (version of 3 weeks ago)
Metalnx database: MySQL 5.7.21
iRODS 4.2.8 cluster

Is there something we can do to fix this errors?

**Comment by trel** [comment]
Oh, so the specific query that Metalnx is trying to use... isn't MySQL-approved... that's quite possible.

It might need a slightly different syntax.

For...
```
SELECT R_USER_MAIN.user_name, R_USER_MAIN.user_id, R_OBJT_ACCESS.access_type_id, R_USER_MAIN.user_type_name, R_USER_MAIN.zone_name, R_COLL_MAIN.coll_name, USER_GROUP_MAIN.user_name, R_COLL_MAIN.coll_name FROM R_USER_MAIN AS USER_GROUP_MAIN JOIN R_USER_GROUP JOIN R_USER_MAIN ON R_USER_GROUP.user_id = R_USER_MAIN.user_id ON USER_GROUP_MAIN.user_id = R_USER_GROUP.group_user_id JOIN R_OBJT_ACCESS ON R_USER_GROUP.group_user_id = R_OBJT_ACCESS.user_id JOIN R_COLL_MAIN ON R_OBJT_ACCESS.object_id = R_COLL_MAIN.coll_id WHERE R_COLL_MAIN.coll_name = ? AND R_USER_MAIN.user_name = ? ORDER BY R_COLL_MAIN.coll_name, R_USER_MAIN.user_name, R_OBJT_ACCESS.access_type_id DESC
```

Online checkers...
- https://www.piliapp.com/mysql-syntax-check/ returns the same error as above
- https://en.rakko.tools/tools/36/ says it's fine

**Comment by michael-conway** [comment]
This is indeed a specific query issue. There was some work done a while back to isolate these queries and to create a factory/provider model so that a different implementation of specific queries could be implemented for other target databases.

see https://github.com/DICE-UNC/jargon-irods-ext/tree/master/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/utils

I personally would submit that getting rid of some of these unnecessarily fancy specific queries be the higher priority and focus on getting rid of the rest of the metalnx database and refacing the collection browsing as we complete the gallery browsing.

**Comment by trel** [comment]
Agreed.

Big Picture Goals:
- Remove the Metalnx database entirely.
- Remove the need for rodsadmin privileges to run Metalnx (required by using specific-queries)

**Comment by paulborgermans** [comment]
Actually, the (upstream) implementation for MySQL is missing alltogether:

https://github.com/DICE-UNC/jargon-irods-ext/blob/4a20477a4a4dcbb3eb59cfcf73b7ebdcdbd584d2/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/utils/SpecificQueryProviderFactoryImpl.java#L44-L53

I looked at the PostgreSQL implementation and it is pretty much generic, so my guess is that it is easy to add for MySQL. The build is not that trivial to make it work locally for me though

**Comment by peterverraedt** [comment]
See https://github.com/DICE-UNC/jargon-irods-ext/pull/29

**Comment by trel** [comment]
DICE-UNC/jargon-irods-ext#29 was merged - is this still an issue in Metalnx?   any further action needed?

**Comment by korydraughn** [comment]
Is this still an issue?

**Comment by trel** [comment]
Probably safe to close, as long as we're sure we're pulling in the fixed code when building.

There have been three releases of metalnx (2.5.0, 2.5.1, and 2.6.0) since https://github.com/DICE-UNC/jargon-irods-ext/pull/29 was merged.
