### ISSUE TITLE
iRODS metadata/properties search Q: Is (or could) it be possible to search using both AVUs and properties at once?

### ISSUE THREAD

**Issue by BlakeGFitch** [irods-contrib/metalnx-web#182]
Hello Metalnx Team,

I see that Metalnx allows search using AVU metadata and on another tab, search based on properties like strings in the directory structure.

Is it possible to use both AVUs and properties simultaneously to search?

Thanks!
Blake

**Comment by michael-conway** [comment]
Hi Blake not in the original, however we're working with the Consortium
folks on indexing so that there is an elastic search index that you can
plug in to do just this. In addition it already has a facility for really
simple pluggable search microservices so that you could plug in site
specific searches, for example we have a projects search and a sequencing
data search plugin along with a straight props and AVU search. I can show
you that if you'd like via DM, we use this at NIEHS.

**Comment by BlakeGFitch** [comment]
Hi Micheal,

Thank you for the quick response!

I don't think we need it right away, but it helps to know it is on the way. I'm thinking through the layout for some MRI data in iRODS and the question came up in thinking about what should be a directory in a path vs what should be an AVU. Also, I find my self putting repetitive (with the directory/collection structure) information in the AVUs to make directories searchable. 

Overall the relationship between directories or path components and AVUs is sort of interesting. What I'm coming up with is that directory/collection structure should be used when access permissions might be involved. But otherwise, keep things flat and use AVUs because they are more searchable. Are there any rules of thumb for this level of design?

Best,
Blake

**Comment by michael-conway** [comment]
I'll close this. Pluggable search is enabled, there is a current effort to normalize the general metadata search schema but we can share our current indexer and search plugin if interested.

**Comment by trel** [comment]
I'm going to reopen this as we are considering reworking the integrated search page as well.

An additional request is to allow both boolean 'AND' and 'OR' searches. 

The current implementation only allows for 'OR', which is good/better for lay or less sophisticated searchers, but not as powerful or targeted for the searchers who want to be very specific.

**Comment by korydraughn** [comment]
Can this be closed now that #267 is merged?

**Comment by trel** [comment]
definitely.
