### ISSUE TITLE
CSV download of Metadata downloads data of parent collection instead of current collection

### ISSUE THREAD

**Issue by kuntzagk** [irods-contrib/metalnx-web#187]
Hi,

if I display the metadata of a collection using the "View Info" button 
![MetaLnx_csv_1](https://user-images.githubusercontent.com/822870/107627965-4712b280-6c60-11eb-80da-d9ef56ae0df9.PNG)

and then press the "CSV" button 

![MetaLnx_csv_2](https://user-images.githubusercontent.com/822870/107627985-4e39c080-6c60-11eb-8508-333940b6ca95.PNG)
 I actually get the metadata of the parent collection (empty in my example). This is also indicated by the "File path" value in the CSV.

![MetaLnx_csv_3](https://user-images.githubusercontent.com/822870/107628001-542fa180-6c60-11eb-9450-c77dbac626e0.PNG)

When I enter the Metadata-View by pressing the little-i Button everything works as expected.

**Comment by kuntzagk** [comment]
The CSV download button get's mapped to an URL 
I think the problem lies in here (in MetadataController.java)

`        @RequestMapping(value = "/exportToCSV")
        public void exportToCSV(final HttpServletResponse response) throws IOException, DataGridException {
                String filePath = collectionController.getCurrentPath();
`
The path is not taken from the "path" attribute of the HTML request but from some "current" path that is probably still referencing the parent collection.

**Comment by trel** [comment]
I reproduced this locally.

It is exactly as you describe
- the 'i' entrypoint uses the correct 'current' collection path.
- the 'get info' button 'in' the listing of a parent collection uses the incorrect parent collection path.

**Comment by korydraughn** [comment]
This behavior happens because the **View Info** button within the listing never triggers an update to the **currentPath** member variable of **CollectionController** while the **i** button does. So, depending on how you reached the collection info page, the path used to produce the CSV file will reference either a parent path or the current path.
