### ISSUE TITLE
Redo collection browser

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#188]
Remove existing collection browse view and replace with Vue.js as in thumbnail viewer.

**Comment by michael-conway** [comment]
This is the place to get rid of most of the rest of the Metalnx database and performance can really be improved. I am super keen to take the insights we got from cloud browser and be able to save searches, including from indexing, as collections here. We have use cases.

**Comment by trel** [comment]
duplicate of #63
