### ISSUE TITLE
configuration option to hide certain AVUs from rodsusers

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#191]
Some deployments use AVUs for administrative purposes.

This could be considered ACLs on AVUs... or... a simpler Metalnx-only solution would be to define a list of attributes that are not shown in Metadata pages for data objects or collections.

metalnx.properties item might be:
`metalnx.avu.attributes_to_hide`

**Comment by michael-conway** [comment]
is there a place for a convention on attribs with . prefix, like hidden files (another feature I'd want perhaps at the same time)

e.g. I have an AVU for technical metadata

.CollectionDisposition | Deprecated | irods:TechnicalMetadataSomethingSomething

In this way we can just say any . prefixed attributes denote technical metadata hidden unless rods admin? Like I said, as we move away from the metalnx database such a simple and familiar convention for both metadata and for files might make the world a happier place?

**Comment by trel** [comment]
We could definitely have a convention / default of not showing data objects / collections / attributes that begin with `.`.

Such a convention does not preclude the desire for a setting where administrators can 'hide' some metadata specific to their Zone - something that might predate iRODS or Metalnx - e.g. patient_id, or lat/long, etc.

**Comment by korydraughn** [comment]
Going off of the config properties idea, we could provide three properties that instruct Metalnx on how to hide/mask metadata.
```
metalnx.metadata.mask.scheme    = prefix | regex | explicit
metalnx.metadata.mask.value     = string
metalnx.metadata.mask.delimiter = string
```

### Property: metalnx.metadata.mask.scheme
This applies to attribute names only. If we wanted, we could extend it to values and units, but I feel that isn't necessary.
- `prefix`: Hide things based on the start of the attribute name (similar to the metadata-guard REP)
- `regex`: Hide things based on a regular expression
- `explicit`: Hide things based on exact matches of attribute names

The motivation for providing various schemes being performance.

### Property: metalnx.metadata.mask.value
This property represents the constraint. Lists are indicated by the use of `metalnx.metadata.mask.delimiter` in the string.

Only the `prefix` and `explicit` schemes support lists.

### Property: metalnx.metadata.mask.delimiter
This gives admins flexibility for cases where using the default delimiter results in incorrect parsing of `metalnx.metadata.mask.value`.

A semicolon may serve as a good default.

**Comment by trel** [comment]
This seems very nice - need to define a default for each property (in case not defined).  I suggest scheme should be ‘none’.

Would we also need to prevent a rodsuser from adding/editing/saving AVUs that would not be shown.

**Comment by korydraughn** [comment]
Setting scheme to none sounds reasonable.

> Would we also need to prevent a rodsuser from adding/editing/saving AVUs that would not be shown.

I'm not sure. Adding seems fine, but not editing/removing. This feels like it should be an option for the admin to configure.

The other option is to make scheme align with the metadata guard and only deal with prefixes. That moves the case for protecting metadata from metalnx to the iRODS server. It also means fewer options for metalnx and pushes the convention of using prefixes to scope metadata. I like this solution. Simpler and harder to break.

**Comment by trel** [comment]
I definitely like the server being in charge and letting metadata_guard do its job.   But metadata_guard only protects writing, not visibility...  Would Metalnx be able to inquire about protected metadata and use the server's setting to hide them as well?  
If so...

1. server would have to expose existing metadata_guard settings

2. metalnx.properties has a setting to hide/show metadata_guard'ed AVUs

    a. if set to 'hide', metalnx would retrieve the setting from the (connected?) server, and not show those AVUs

3. metalnx search has to honor this setting as well?   hmmm....  can't leak information...   starts to get complicated...

**Comment by korydraughn** [comment]
We could make metalnx inquire about metadata_guard configuration, but I don't think that's necessary.

What I'm proposing is that the metadata_guard continues to work as it does today and we only teach metalnx to hide metadata through the use of prefixes.

That makes metalnx follow the same design as the metadata_guard which means as long as the admin uses the same prefixes everywhere, hiding and guarding metadata is achieved.

**Comment by trel** [comment]
Got it - two sources of truth (but prefixes only) - up to the admin to keep them in sync.... seems reasonable.

And metalnx would still need to filter/hide via search, as well.

**Comment by korydraughn** [comment]
Right.

**Comment by trel** [comment]
So...

The server is protecting against AVU writes/edits (metadata_guard).

The client (in this case, metalnx) is protecting against AVUs even being seen (property to-be-named).

--

candidate property pairs...
- `metalnx.metadata.mask.prefixes = ''`
- `metalnx.metadata.mask.delimiter = ';'`
or
- `metalnx.hide_metadata.prefixes = ''`
- `metalnx.hide_metadata.delimiter = ''`

so a real usage might be:
 - `metalnx.metadata.mask.prefixes = 'irods::;metalnx::;secretstuff::'`
 - `metalnx.metadata.mask.delimiter = ';'`

**Comment by korydraughn** [comment]
Exactly.

**Comment by korydraughn** [comment]
Reopening because the current implementation hides metadata from rodsadmin too.

Will make it so that metadata is only hidden if the user is not a rodsadmin.
