### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by NhlamuloChauke** [irods-contrib/metalnx-web#196]
Hi I was compilling Metalnx(metalnx-web-1-stable) version 4.
I am getting the following error with the command:

`mvn clean generate-sources package -Ppreprod -Dmaven.test.skip=true `

Failed to execute goal on project emc-metalnx-shared: Could not resolve dependencies for project com.emc.metalnx:emc-metalnx-shared:jar:1.4.0: Failed to collect dependencies at com.emc.metalnx:emc-metalnx-services:jar:1.4.0 -> org.irods.jargon:jargon-core:jar:4.1.10.0-RELEASE -> com.claymoresystems:puretls:jar:1.1: Failed to read artifact descriptor for com.claymoresystems:puretls:jar:1.1: Could not transfer artifact com.claymoresystems:puretls:pom:1.1 from/to ci.dev.repository (http://ci-dev.renci.org/nexus/content/repositories/public): ci-dev.renci.org: Unknown host ci-dev.renci.org -> [Help 1]

Your response will be highly appreciated

**Comment by kuntzagk** [comment]
Hi,

does your machine have direct internet connection or through a proxy? 
I think I had similar errors when building docker image from source. 
I had to set the http_proxy and https_proxy variables to make it work.

**Comment by NhlamuloChauke** [comment]
@kuntzagk  I am using Direct internet. How to set the http_proxy and https_proxy variables? @kuntzagk  can you help me with that. much appreciated.

**Comment by NhlamuloChauke** [comment]
Hi  Andreas,

I am using a direct internet connection.
How do you set http_proxy and https_proxy ?

**Comment by kuntzagk** [comment]
If your using direct internet without proxy you do not neet proxy settings. 
It seems that ci-dev.renci.org really does not exist. I also cannot find any reference to it in the code.

**Comment by trel** [comment]
Why are you interested in building the old version of Metalnx?

The ci-dev machine at renci has been gone for 2-3 years.

Building 2.2.0 or master is recommended.

**Comment by michael-conway** [comment]
I'll try to go black in my memory, I want to say some of those libraries
moved...Better to build a later version though!
