### ISSUE TITLE
Upload works only for some file types.

### ISSUE THREAD

**Issue by fh-afk** [irods-contrib/metalnx-web#201]
I just installed metalnx and I am in the state of trying out its capabilities. I can upload jpg, pdf or gif files (file name endings do not matter), but when I try random data or mp4s, avi or mp3 the process hangs like this

![image](https://user-images.githubusercontent.com/79457640/108713940-32b09e80-7519-11eb-8698-7f15733a8a0a.png)

I do not get any error in rodsLog and the only thing suspicious from the docker container is:

`metalnx_1  | 2021-02-22 13:20:24 WARN  ResourceAOImpl:621 - unable to format resourceFreeSpace for value: setting to 0`

I already tried switching the settings

`irodsext.datatyper.detailed.determination` and
`irodsext.datatyper.persist.data.types`

in metalnx.properties, it does not change the behaviour. At this moment, I am running out of ideas. I would very much prefer a solution that is agnostic about file types.
Side Info: using iput instead of metalnx to get those files into IRODS does not cause any issues.

**Comment by michael-conway** [comment]
this is probably length related...I've got some upload changes for
upload/download length pending so I'll link this to that issue and follow up

**Comment by fh-afk** [comment]
Thanks for the quick reply! I can confirm that a small random file lile 
`dd if=/dev/urandom of=test bs=5K count=1`
uploads as expected. This is probably insufficient for our scientists, but I have to try out more. I will close this with the suggestion to implement throwing an error instead of just hanging and letting the user wait in such situations.
