### ISSUE TITLE
search results using resc_name, needs to be updated to resc_id

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#203]
Since iRODS 4.2.0, iRODS has no longer used `r_data_main.resc_name`.

iRODS now uses `r_data_main.resc_id` which needs to be resolved to a name from `r_resc_main`.

This means that there are duplicate results in the the search results and the Resource column shows `EMPTY_RESC_NAME`.

**Comment by korydraughn** [comment]
how do you trigger this?

**Comment by trel** [comment]
I think... using AVU search... have 2-3 data objects (with more than one replica each) that should return given a particular search.

You will see results *per physical replica*, rather than *per logical data object*.

```
$ ils -L boo
  rods              0 demoResc         1693 2021-04-20.11:51 & boo
        generic    /var/lib/irods/Vault/home/rods/boo
  rods              1 pt;compResc;cacheResc            6 2021-04-20.11:51 & boo
        generic    /tmp/anotherRescVault/home/rods/boo
  rods              2 pt;compResc;archiveResc         1693 2021-04-20.11:51 & boo
        generic    /tmp/thirdresc/home/rods/boo

$ imeta ls -d boo
AVUs defined for dataObj /tempZone/home/rods/boo:
attribute: a
value: v
units: u
----
attribute: apples
value: bananas
units: 
----
attribute: key2
value: value3
units: 
```

<img width="860" alt="Screen Shot 2021-04-30 at 8 45 37 AM" src="https://user-images.githubusercontent.com/55238/116696967-92e81480-a990-11eb-90ee-426b1a5db3dc.png">

(ignore the replicas both marked good with different sizes... that's just bad info in the catalog)

**Comment by korydraughn** [comment]
thanks
