### ISSUE TITLE
Metalnx and iRODS federations, configurable breadcrumbs

### ISSUE THREAD

**Issue by chStaiger** [irods-contrib/metalnx-web#22]
I am using Metalnx as a front end for an iRODS instance (eveZone) which is federated with another iRODS instance (bobZone). 
However, Metalnx does not show the contents of the remote collection:

```sh
ubuntu@eve-server:~$ ils /bobZone/home/christine#eveZone
/bobZone/home/christine#eveZone:
  install-Metalnx.pdf
  C- /bobZone/home/christine#eveZone/testcoll
```

![screen shot 2017-08-16 at 15 30 47](https://user-images.githubusercontent.com/8696302/29365671-1ccf4174-8298-11e7-88cf-5e9469d29a46.png)

Funnily, I could upload the pdf in the remote collection via Metalnx!

**Comment by michael-conway** [comment]
I want to include this in the collection browser redesign effort and start showing federated zones pretty soon. Will propose a federation milestone

**Comment by michael-conway** [comment]
Folding in this request:
Hide zone from the breadcrumb (for non admin users or change it to something simple)

So these two things need to be accommodated. The plan would be to make the zone display an 'advanced view' feature and then test out the federation browsing in the advanced feature set.

**Comment by trel** [comment]
@michael-conway Is there anything else we want to do for this?   If so, let's enumerate the remaining work/tasks/desire and I'll bump it again.

Otherwise, I'll close.

**Comment by trel** [comment]
Closing.    We'll open a new issue if there is more to be done.
