### ISSUE TITLE
new thumbnail view icon wraps to next 'line'

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#233]
it should sit alongside the other three icons in the upper right...

<img width="214" alt="Screen Shot 2021-05-05 at 12 31 18 PM" src="https://user-images.githubusercontent.com/55238/117176463-ec3fb180-ad9d-11eb-9b03-7dfcd477f422.png">

**Comment by connectbo** [comment]
Fixed in #229 .
