### ISSUE TITLE
USER_INVALID_USERNAME_FORMAT on meta data or properties search

### ISSUE THREAD

**Issue by r5r3** [irods-contrib/metalnx-web#240]
iRODS version: 4.2.8
Metalnx version: 2.3.0 (docker container latest version)

The logs of metalnx are showing the following error:

```
2021-05-21 08:11:20 INFO  SpecQueryServiceImpl:223 - countItemsMatchingFileProperties()
2021-05-21 08:11:20 WARN  IRODSSession:572 - closing session that is already closed, silently ignore
2021-05-21 08:11:20 INFO  SslConnectionUtilities:175 - createSslSocketForProtocolAndIntegrateIntoProtocol()
2021-05-21 08:11:20 INFO  SslConnectionUtilities:177 - have SSL socket, introduce as the iRODS connection in the provided protocol
2021-05-21 08:11:20 INFO  AESKeyGenerator:53 - generateKey()
2021-05-21 08:11:20 ERROR AdminServicesImpl:72 - Could not instantiate CollectionAndDataObjectListAndSearchAO:
org.irods.jargon.core.exception.JargonException: error code received from iRODS:-319000
....
```

On the iRODS server the following error is recorded:

```
May 21 08:11:20 pid:19529 NOTICE: rsAuthCheck: chlCheckAuth status = -319000
May 21 08:11:20 pid:19529 remote addresses: 10.153.17.4, 10.153.52.49 ERROR: [-]        /irods_git_repo/server/api/src/rsAuthResponse.cpp:75:int rsAuthResponse(rsComm_t *, authResponseInp_t *) :  status [USER_INVALID_USERNAME_FORMAT]  errno [] -- message [rcAuthCheck failed.]
        [-]     /irods_git_repo/plugins/auth/native/libnative.cpp:558:irods::error native_auth_agent_response(irods::plugin_context &, authResponseInp_t *) :  status [USER_INVALID_USERNAME_FORMAT]  errno [] -- message [rcAuthCheck failed.]
```  

Except for searching, Metalnx seems to work normal. Files and collections are shown. Downloads are possible, etc...

**Comment by trel** [comment]
That is a weird error - haven't seen that before.

What database is iRODS configured to use in this deployment?

**Comment by r5r3** [comment]
iRODS is using a MariaDB Database (version 10.5.8). 

Some more infos:
- searching for meta data on the command line using icommands works.
- the autocomplete feature in Metalnx works. Available attributes and their values are correctly shown.

**Comment by trel** [comment]
This could be fixed by the work in https://github.com/irods-contrib/metalnx-web/pull/267

Let's test again once that is merged...

**Comment by yr-wang-hit** [comment]
We have met the same error. Really strange and Search Function is now unavailable.

**Comment by korydraughn** [comment]
Can you explain what you mean by **Search Function is now unavailable**?

Is there no Search UI at all?
Or, when you attempt to use the Search UI, you get an error?

Are you running Metalnx with #267 included? If so, can you share the log output?

**Comment by trel** [comment]
Bumping to 2.6.0 for now - not sure if we've fixed whatever the original issue was.

**Comment by yr-wang-hit** [comment]
sorry for late response.

Everything goes well after pulling latest resource and the issue has been fixed for me.

thanks.

**Comment by trel** [comment]
Excellent.   Closing!
