### ISSUE TITLE
packstruct/XML communication fails with 4.2.9/4.3.0

### ISSUE THREAD

**Issue by peterverraedt** [irods-contrib/metalnx-web#245]
Metalnx (jargon) communication with irods fails on special characters because the changed XML encoding in irods 4.2.9 is not reflected in the java code base.

See [org.irods.jargon.core.packinstr.Tag] for package encoding - translation of `&apos;` is not correct (among others).

The issue appears because jargon does not send a fixed client version in [org.irods.jargon.core.packinstr.StartupPack] but just the string `"d"`. The protocol negotiation therefore does not work.

Please either fix XML encoding or provide a way to send a client version (e.g. set to irods4.2.8 until XML encoding is fixed).

[org.irods.jargon.core.packinstr.Tag]: https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/packinstr/Tag.java
[org.irods.jargon.core.packinstr.StartupPack]: https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/packinstr/StartupPack.java#L59

**Comment by trel** [comment]
But ... what happened?    Did you get it to work as expected?   Is this something broken that needs to be fixed?

**Comment by peterverraedt** [comment]
Sorry, evening daddy duties came in way of immediate explanation.

This was a false positive - I was testing with a directory containing special utf8-characters in filenames, and this folder didn't show up correctly in metalnx. I did not notice yet the same was true for accessing that directory just by the icommands and blamed it on metalnx. However, it was our patch of the setup scripts to add `Charset=UTF-8` to the odbc configuration for mysql that failed to apply - making the odbc connector to return gibberish and irods to fail.

While it remains true (I think) that metalnx communicates with the pre-fixed xml encodings, it should not be marked as a bug anymore.

**Comment by trel** [comment]
Ah, very good.   Thanks.
