### ISSUE TITLE
Download multiple files results in tar with name .zip

### ISSUE THREAD

**Issue by peterverraedt** [irods-contrib/metalnx-web#247]
In case multiple files are selected under "Collections", and Action > Download is chosen, the resulting file has a .zip-extension but is actually a tar file.

See <https://github.com/DICE-UNC/jargon-irods-ext/blob/master/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/CollectionServiceImpl.java#L768-L769> for relevant code, removing these lines results in a .tar-file that actually is a tar file.

The reason for this seems to be that in <https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/BulkFileOperationsAOImpl.java#L102-L133> the given bundleType parameter is only used to write to the log, so the standard behaviour of irods will be used to create a tar.

Tested with metalnx 2.4.0.

**Comment by michael-conway** [comment]
I'll pick this one up

**Comment by korydraughn** [comment]
@michael-conway Any progress on this?

**Comment by michael-conway** [comment]
Let's chat Monday if this needs to be bumped I can do it

**Comment by michael-conway** [comment]
....have a pull request on this

**Comment by trel** [comment]
If this is working - please link to the PR/commit that fixes it - presumably in jargon proper?

I'm having a hard time following where this was addressed.

**Comment by trel** [comment]
Looks like the following commit in `jargon-irods-ext` addressed the issue by changing the default `bundleType` from ZIP to TAR.

https://github.com/DICE-UNC/jargon-irods-ext/commit/b17fb807441b8f120611c38e3ee7e7758547a3f5

```diff
-	zipServiceConfiguration.setPreferredBundleType(BundleType.ZIP);
+	zipServiceConfiguration.setPreferredBundleType(BundleType.TAR);
```
