### ISSUE TITLE
Metalnx needs to have the same behaviors and results for the permission management like how iCommands - ichmod does

### ISSUE THREAD

**Issue by mstfdkmn** [irods-contrib/metalnx-web#255]
For the data object and collection that a user has “own” access right (granted by uploading data or by creating a collection), a user can change the access right to other options (read/write/own) as long as he/she stays on the same screen. Once he/she click on any other page/tab after he/she change permission from “own” to “write/read”, it is not possible any more to take his/her own right back. However this is possible by iCommand.

As long as you are on the same screen, you can switch to any other access type.

![image](https://user-images.githubusercontent.com/49678793/125312376-812dd080-e334-11eb-8dcd-7bfdba2cbb28.png)

Once you click on any other tab or screen, you cannot change the permission type that you set because the relevant field is disabled (even for the "write" access type).

![image](https://user-images.githubusercontent.com/49678793/125312512-a0c4f900-e334-11eb-815a-91d6a79ada6c.png)

However you can change back to your initial access type by using iCommands.

![image](https://user-images.githubusercontent.com/49678793/125312739-d79b0f00-e334-11eb-93a8-31b13cc80eea.png)

Another issue here is (this seems closely related to the issue above);

For the data object and collection that a user has “own” access right, the user either should be warned or should be blocked when the user choose the “none” option in the permission column. Because as soon as a user change his “own” right to “none”, this data object/collection will disappear. Then only the admin users or the users who have “own” access right on that item can bring it back for the mentioned user. However a user take the permission back by iCommand. 

![image](https://user-images.githubusercontent.com/49678793/125314490-8429c080-e336-11eb-8c91-784ea719c267.png)

After you removed your permission, if you click on any other tab you will get the 500 server error below. And the only way to go back to Metalnx is to connect to it again by new authentication.

![image](https://user-images.githubusercontent.com/49678793/125315019-03b78f80-e337-11eb-9d00-860e7d5ad11f.png)

By the way as figure it out parameter name used to remove an access right by Metalnx is “none” whereas it is “null” by iCommands.

Thank you.

Tested both in 4.2.8 - 2.4.0 and in 4.2.9 - 2.4.0. And ICAT is MySQL.

**Comment by korydraughn** [comment]
The behavior of Metalnx is correct here. The icommands should not allow that because it bypasses the permission model, hence https://github.com/irods/irods/issues/6579.

To help users with this, we're planning on showing a confirmation popup when Metalnx detects a downgrade.
