### ISSUE TITLE
After delete a data object, you are not forwarded to the collection that you are in

### ISSUE THREAD

**Issue by mstfdkmn** [irods-contrib/metalnx-web#256]
After you delete a data object, you are supposed to be automatically forwarded to the collection that you are in. But this doesn't happens when you inside the view info.

With the delete option by using view info/action/delete you cannot easily go back to the screen that you are in. You have to click on the “Go back to Collection Home” on the wrongly named popped-up message. And this is not user friendly when you are working on embedded collections. However this doesn’t happen with deleting by selecting tick box/Action/Delete.

![image](https://user-images.githubusercontent.com/49678793/125316842-c6ec9800-e338-11eb-9d69-dd2ea9bb025e.png)

You have to click on the "Go back to Collection Home” to be back to Metalnx.
![image](https://user-images.githubusercontent.com/49678793/125318153-e1734100-e339-11eb-9e66-bfd586c33c48.png)

Thanks.

Tested both in 4.2.8 - 2.4.0 and in 4.2.9 - 2.4.0. And ICAT is MySQL.

**Comment by korydraughn** [comment]
Given how deletion works in this case, I've updated the application to redirect to the collection view automatically after a successful deletion. I will review this issue one more time before closing, in case there is a better solution.

**Comment by trel** [comment]
better solution: just go to the parent of the data object that was being deleted?

**Comment by korydraughn** [comment]
I've created a PR with the necessary changes. Please give it a look.
