### ISSUE TITLE
Edit functionality provided by “Preview” tab for an editable file type must not appear in case you have read only access

### ISSUE THREAD

**Issue by mstfdkmn** [irods-contrib/metalnx-web#257]
You can see edit mode inside the “Preview” even for the editable data objects (files) that you have only read access to. Nonetheless you cannot modify because it throws “500 - Internal Server Error”.

Once you have only "read" access,

![image](https://user-images.githubusercontent.com/49678793/125321975-86dbe400-e33d-11eb-9488-e7fc7e39185a.png)

you should not have/see the editable mode of the preview.

![image](https://user-images.githubusercontent.com/49678793/125322054-9eb36800-e33d-11eb-9666-4934ce82b997.png)

After you edit, if you click on the "save", you will get 500 server error.

![image](https://user-images.githubusercontent.com/49678793/125322138-b854af80-e33d-11eb-8939-afd2229d5e65.png)

Thank you.

**Comment by trel** [comment]
@connectbo please close if this is complete.

**Comment by connectbo** [comment]
@trel It's complete. No 'save' or 'cancel' button if you have read only access. Seems like I don't have the permission to close this issue.
