### ISSUE TITLE
Property based search in AVU search should not show all results - not more than granted permission rights

### ISSUE THREAD

**Issue by mstfdkmn** [irods-contrib/metalnx-web#258]
Property based search in AVU search gives users (rodsuser) possibility to see other users’ all collection and data objects structure and name. To some extent this might be okay. But I think this is more than "needs to know principle". iCommands search by iquest doesn’t provide the same result. The iquest query works according to the granted access permissions.

Make the query based on the path parameter including a targeted user name:

![image](https://user-images.githubusercontent.com/49678793/125581737-15818c1b-8b7c-4a99-82c6-5896ca5ce083.png)

See all the collections and data objects of the queried user. As seen, if the user who makes query has access right to any objects, those objects appear in a blue color and so that clickable:

![image](https://user-images.githubusercontent.com/49678793/125582086-703d7036-5b40-4f61-ae21-a98805974750.png)

You can see data objects as well:

![image](https://user-images.githubusercontent.com/49678793/125582744-501b4294-8f5f-48e2-b2c3-728bd4e296db.png)

However iCommands - iquest gives the results only for the objects that the query making user has access to.

`iquest "%s/%s" "SELECT COLL_NAME, DATA_NAME where COLL_NAME like '%userName%'"`

![image](https://user-images.githubusercontent.com/49678793/125583014-399e90e3-ee23-4617-9913-a1cb413114f2.png)

We think that extensive search options of Metalnx should work according to the access rights like what we have in other clients, i.e., iCommands. How do you evaluate this?

**Note:** Tested both in 4.2.8 - 2.4.0 and in 4.2.9 - 2.4.0 and the db is MySQL.

Thanks.

**Comment by mstfdkmn** [comment]
A minor point:

On this screen the column name "File Type" should be "Object Type" and the value "file" should be "data object" for the sake of consistency.

**Comment by korydraughn** [comment]
Please take a look at the following PR: https://github.com/irods-contrib/metalnx-web/pull/267

**Comment by korydraughn** [comment]
This issue can be closed due to #267.

**Comment by trel** [comment]
Ah, very nice.
