### ISSUE TITLE
AVU search should show only single replica (logical path)

### ISSUE THREAD

**Issue by mstfdkmn** [irods-contrib/metalnx-web#259]
All the search results based on AVU are for all replicas. But the end user should only take care and know the logical representation, meaning they should see only one result as what they see by other clients.

Metalnx brings two replicas:

![image](https://user-images.githubusercontent.com/49678793/125597778-b74375f6-a105-455f-bf91-6f910f2133f4.png)

iCommand brings the one replica:

![image](https://user-images.githubusercontent.com/49678793/125598295-1bca9fe0-1f50-4225-aa4c-becebcba45e4.png)

![image](https://user-images.githubusercontent.com/49678793/125597923-efa22474-578e-4d2f-a0e0-c7ff6c357203.png)

Also all search results for data objects show EMPTY_RESC_NAME instead of one of the posix that we use as resource. Why does it bring this empty column? There could be an issue by not updating the resource name column with its associated value.
https://github.com/irods/irods/blob/32cc2bd18e43aaaa42f002d07996343a05066646/scripts/update_deprecated_database_columns.py

**Note**: Tested in 4.2.8 - 2.4.0 and the db is MySQL.

Thanks.

**Comment by korydraughn** [comment]
Please take a look at the following PR: https://github.com/irods-contrib/metalnx-web/pull/267

We've reworked the interface to function closer to iquest.
