### ISSUE TITLE
Metalnx-msi installation problem

### ISSUE THREAD

**Issue by aiteteji** [irods-contrib/metalnx-web#26]
I ran into a problem now while installing Metalnx-msi. The installation guide says, in order to verify the microservice installation, one should check "/var/lib/irods/plugins/microservices" to be sure that the .so files ( e.g libmsiget_illumina_meta.so..) are there. In my case, I found them in "/usr/lib/irods/plugins/microservices". Do you have idea how I can correct this? How do I make tomcat find the path? I copied them to the "/var/lib/irods/plugins/microservices" directory, but it didn't show on the metalnx-web.
The problem happen while installing on different systems with tomcat7 and tomcat8.

ps: it will be great if you include the download link on the installation guide page too.

**Comment by sgworth** [comment]
If my memory serves the problem is not with anything you did nor your
Tomcat setup.  If memory serves, in iRODS 4.2 the microservices location
was moved from /var/lib to /usr/lib and the documentation was last updated
for iRODS 4.1 (where things were in /var/lib/irods/plugins/microservices.
If you will copy the .so files from the /var/lib location to the
/usr/lib/irods/plugins/microservices directory they should work.  If not
please report back.  NOTE:  The msi files need to be copied into the
/usr/lib location on your iCAT and all resource servers.

Thanks for the note about the documentation changes.

**Comment by aiteteji** [comment]
Thanks for the reply. I have only one iRODS server (4.1.11) where all resources including iCAT are on the same server. My microservices reside in /var/lib/irods/plugins/microservices but during installation, metalnx-msi installed the plugin in /usr/lib. 
I have coppied all the *.so files to the /var/lib/irods/plugins/microservice, the metalnx-web app still cannot detect it. It showed "Metalnx MSI package not installed." 
Here is the error I got on rodsLog:

getVersion{
  *version="";
  remote("irods-server", "") {
    msiobjget_version(*version);
  }
}
, status = -1097000
Nov 20 15:45:25 pid:13403 ERROR: [-]    iRODS/server/re/src/rules.cpp:670:actionTableLookUp :  status [PLUGIN_ERROR]  errno [] -- message []
        [-]     iRODS/server/re/src/irods_ms_plugin.cpp:110:load_microservice_plugin :  status [PLUGIN_ERROR]  errno [] -- message [Failed to create ms plugin entry.]
                [-]     iRODS/lib/core/include/irods_load_plugin.hpp:194:load_plugin :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/var/lib/iro$

Nov 20 15:45:25 pid:13403 ERROR: executeRuleAction Failed for msiobjget_microservices status = -1097000 NO_RULE_OR_MSI_FUNCTION_FOUND_ERR
Nov 20 15:45:25 pid:13403 NOTICE: executeRuleBody: Microservice or Action msiobjget_microservices Failed with status -1097000
Nov 20 15:45:25 pid:13403 NOTICE: execRuleNodeRes: applyRule Failed: remExec with status -1097000
Nov 20 15:45:25 pid:13403 DEBUG: error: cannot find rule for action "msiobjget_microservices" available: 102.
line 1, col 4
    msiobjget_microservices(*msis);
    ^

Nov 20 15:45:25 pid:13403 NOTICE: execMyRule remExec{
    msiobjget_microservices(*msis);
  } Failed with status -1097000
Nov 20 15:45:25 pid:13403 ERROR: rsExecMyRule : execMyRule error for remExec{
    msiobjget_microservices(*msis);
  }, status = -1097000
Nov 20 15:45:25 pid:13403 ERROR: executeRuleAction Failed for remoteExec status = -1097000 NO_RULE_OR_MSI_FUNCTION_FOUND_ERR
Nov 20 15:45:25 pid:13403 NOTICE: executeRuleBody: Microservice or Action remoteExec Failed with status -1097000
Nov 20 15:45:25 pid:13403 NOTICE: execRuleNodeRes: applyRule Failed: getMicroservices with status -1097000
Nov 20 15:45:25 pid:13403 DEBUG:
Nov 20 15:45:25 pid:13403 NOTICE: execMyRule @external
getMicroservices{
  *msis="";
  remote("irods-server", "") {
    msiobjget_microservices(*msis);
  }
}
 Failed with status -1097000
Nov 20 15:45:25 pid:13403 ERROR: rsExecMyRule : execMyRule error for @external
getMicroservices{
  *msis="";
  remote("irods-server", "") {
    msiobjget_microservices(*msis);
  }
}
, status = -1097000
Nov 20 15:45:25 pid:13403 NOTICE: readAndProcClientMsg: received disconnect msg from client

Hope you can help with the problem. Thanks

**Comment by michael-conway** [comment]
migrating issue over to https://github.com/irods-contrib/metalnx-msi/issues/5
