### ISSUE TITLE
Not able to view Metadata with "+" in the file name via Metalnx Gui

### ISSUE THREAD

**Issue by RitiMehrotra** [irods-contrib/metalnx-web#261]
Dear Team @trel

It has been reported and identified that when user is trying to view the metadata for some files using Metalnx , it throws an error (please see attached).  There is a '+' in those files names, whereas the files in the same location without + in their filenames, metadata can be viewed without such error.

![metalnxError](https://user-images.githubusercontent.com/88081147/127654131-42300f3a-5eca-4c28-a851-89babfd9da8d.PNG)

**Comment by trel** [comment]
Probably just a parsing error - thanks - we'll find it and fix it.

**Comment by korydraughn** [comment]
@RitiMehrotra

Q. What version of Metalnx are you running?
Q. What version of iRODS are you running Metalnx against?

**Comment by RitiMehrotra** [comment]
Hello,



Metalnx version is 2.2.1 & iRODS version is 4.2.8



Thank You. Have a Good Day!



Mit freundlichen Grüßen / Best Regards,



Ritika Mehrotra

--------------------------------------------------------------------------------------------------------------

TATA Consultancy Services Deutschland GmbH, Frankfurt



Contract partner of Bayer AG



On behalf of

Bayer AG

51368 Leverkusen, Deutschland



Cell: +91-9711819845

E-Mail: ***@***.******@***.***>

Web: http://www.bayer.com



Geschäftsführung: Daniel Hartert, Geschäftsführer | Wilhelm Oehlschläger

Vorsitzender des Aufsichtsrats: Wolfgang Nickl

Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 49895

**Comment by korydraughn** [comment]
Thanks. I was able to reproduce.

We will look into fixing this for 2.5.0

**Comment by RitiMehrotra** [comment]
Thank You. Could you please share the tentative timeline of v2.5.0



Thank You. Have a Good Day!



Mit freundlichen Grüßen / Best Regards,



Ritika Mehrotra

--------------------------------------------------------------------------------------------------------------

TATA Consultancy Services Deutschland GmbH, Frankfurt



Contract partner of Bayer AG



On behalf of

Bayer AG

51368 Leverkusen, Deutschland



Cell: +91-9711819845

E-Mail: ***@***.******@***.***>

Web: http://www.bayer.com



Geschäftsführung: Daniel Hartert, Geschäftsführer | Wilhelm Oehlschläger

Vorsitzender des Aufsichtsrats: Wolfgang Nickl

Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 49895

**Comment by trel** [comment]
fixed.

we are hoping to get the next release of metalnx out the door within a month or so.

but of course, you can build and test the master branch as-is.
