### ISSUE TITLE
Slow upload of files

### ISSUE THREAD

**Issue by Patkm** [irods-contrib/metalnx-web#28]
Hello all,
I'm having a big difference between the iput / iget and metalnx-web commands.
When I upload a 1.5GB file via metalnx-web, the loading time is about 3minutes. When I use the iput command on the same file on the same resource from the same client, the time is 23 seconds. Is there a setting on metalnx-web that can explain this difference?
irods: 4.2.1
metalnx-web: 1.4.0.9 on CentOS 7
Thank's!
P.M.

**Comment by michael-conway** [comment]
HTTP upload is a whole different code path than put/get. There are some
stream optimizations that can be done in the code for sure, but it will
never be as fast as the command line or direct programmatic api

**Comment by Patkm** [comment]
Thank's michael,
I understand that the protocols used are different and that we must expect different performances.
I'm just a little surprised by the big gap: the ratio is about 1 to 9.
So I think metalnx-web can not be used to transfer large amounts of data but i note the possible optimizations in the future.
In fact i am looking for solutions to access iRODS from a mixed environment (windows linux and mac). 
Have a good day!
P.M.

**Comment by michael-conway** [comment]
I'm working on MetaLnx over here https://github.com/DICE-UNC/metalnx-web
and talking with Steve about how the iRODS consortium is picking this up,
so it's in a bit of an in-between state right now!

As we go through this, I know that there is a 'packing' input and output
stream that does some buffer optimization for the iRODS protocol that can
see big improvements, and I'm going to make sure that's implemented in
metalnx. But even with optimizations there will always be advantages to
using native iRODS protocol over HTTP, that's true for any back end! So I
expect to get noticable improvements in streaming. Longer term they are
also working on 'chunk' transfers so files can be broken up.

We're also taking iDrop out of mothballs, which is a cross-platform
upload-download client that can do bulk transfers using direct iRODS
protocol including parallel transfer and then the new multipart transfer
when it is available.

Through the iRODS consortium we're spinning up a working group on folks
using interfaces (metalnx and iDrop,etc) and if there are ways to join
efforts that might help all of us!

MC

**Comment by Patkm** [comment]
Thank you for this very encouraging message!
I hope I can contribute one way or another to this project.
P.M.

**Comment by michael-conway** [comment]
Will close this for now. There may be further transfer enhancements down the road, but the master branch now using packing streams.
