### ISSUE TITLE
Uploading large files to Metalnx

### ISSUE THREAD

**Issue by NhlamuloChauke** [irods-contrib/metalnx-web#303]
Uploading 10MB or more than 10MB files and it seems to be hanging. Its says upload ... then says transferring to iRODS and it hangs there.  On iRODS box i created a testfile 100MB uploads via command line no problem
![MicrosoftTeams-image](https://user-images.githubusercontent.com/17588855/155473159-bc1e4ccf-98f4-43b1-bef1-c3f397d67ae1.png)

**Comment by trel** [comment]
We have had a new jargon release to address larger files and parallel transfers.

We will look at an upgrade and it might fix this issue you're seeing as well.

**Comment by NhlamuloChauke** [comment]
HI Turrell,

We are currently running metalnx(version 2.5.1) which is a docker image.

Let us know when you have updated the metalnx with new jargon release

**Comment by trel** [comment]
2.5.1 is the latest version of metalnx - so we will investigate whether your issue can be reproduced.

**Comment by NhlamuloChauke** [comment]
Thanks @trel I will update you

**Comment by trel** [comment]
Thanks for investigating.    We'll work to reproduce.

**Comment by NhlamuloChauke** [comment]
Thanks, please keep us updated

**Comment by trel** [comment]
We discovered via browser inspection / debugging a `413 Request Entity Too Large` error coming from an nginx proxy server.

This was remedied by adding to the nginx configuration:
```
client_max_body_size 0;
```

The default was 1MB and was blocking uploads until we set it to unlimited.

**Comment by NhlamuloChauke** [comment]
@trel thanks
