### ISSUE TITLE
Create branch structure and merge in latest dev stream

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#31]
The current DICE-UNC stream differs significantly now from the original, including the development of these 'home pages' for files and collection, etc.

We'd like to merge this into the irods-contrib stream, q is do we set up a 1-0-0 stable and a 2-0-0 branch structure? I'd consider what we'd merge in a snapshot of the 2-0-0 development stream at this point, looking for about 2 weeks for a beta.

**Comment by sgworth** [comment]
Mike,
Just in case there is someone out there who also copied the Metalnx 1.4.0
tree and is doing their own thing with it I recommend, with Terrell's
agreement, that you put your changes into a R2.0 stream and let's start the
new version of Metalnx on a R2.0 branch.

Best regards,
Steve Worth

**Comment by michael-conway** [comment]
This sounds great, I'll defer to Terrell on branch naming and structure,
and we can thus have changes in a side stream.

I think there may be some period of turbulence before we settle into some
sort of 2.0 candidate and we don't want to be too disruptive!

Next metalnx wg perhaps we can map out the current set of updates and see
how we could tune them to make everyone feel happy?

**Comment by sgworth** [comment]
Understood & agreed.  It makes sense to begin adjusting Metalnx to map
better into the iRODS framework.  Big things are to make sure we document
carefully what is changing so new people can follow the architecture, be
extensible, etc. and also be careful to keep Metalnx such that is works
alongside of iRODS.

SW

**Comment by trel** [comment]
I've created a branch `1-stable` from `1.4.0` release commit 349a0fe9550d33079b87dc564601759f462c25a0.

The `master` branch will begin working towards `2.0.0` and we can branch again when that is stable/released.

This matches the consortium naming conventions.

If there are merges that someone wants to perform against the `1-stable` branch, we'll have that conversation separately.
