### ISSUE TITLE
Framework-driven previews and edit

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#33]
Ability to show in-place editing and previews, able to tap into iRODS policies and pre-generated or on-demand previews.

This is proposed to start with a very basic facility to show images, and can extend to codemirror type in-place editing of text, spreadsheets as seen in Discovery Environment and Cloud Browser.

This can also bring in the iRODS Rule 'fiddle' tool.

**Comment by michael-conway** [comment]
pdf and odf? http://viewerjs.org/

codemirror - https://codemirror.net/

**Comment by michael-conway** [comment]
a standard 'preview for' metadata unit, so that they can be pre-generated or generated on-demand?

**Comment by trel** [comment]
for previews... seems a recurring python server-side rule that follows a well-defined thumbnail naming convention is the most flexible, portable approach.

configuration would then be a matter of defining
- how often
- source format -> target format
- sizes
- source collection
- recursive?
