### ISSUE TITLE
Cannot create a collection with its sub collections

### ISSUE THREAD

**Issue by mstfdkmn** [irods-contrib/metalnx-web#332]
Once a collection with its sub collections wanted to be created Metalnx cannot succeed this whereas iCommands `imkdir -p collection/collection1` and PRC (iRODSPath class) can do.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/49678793/202126389-1207eb49-bda7-4860-a722-dd6688242d50.png">

<img width="496" alt="image" src="https://user-images.githubusercontent.com/49678793/202126520-480d7c6d-be30-4c08-9077-d3d11954972a.png">

However it eliminates extra slashes in the beginning/end of a collection - paths.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/49678793/202130063-c2ad9290-ba5e-4a0f-adf5-39cd032902c7.png">

**Comment by trel** [comment]
Oh, agreed - that is silly.   Will fix.   Thanks.

**Comment by JustinKyleJames** [comment]
Can someone assign this to me?  I can't seem to assign.

**Comment by korydraughn** [comment]
Done.

**Comment by JustinKyleJames** [comment]
This has been fixed.  The pull requests are #345 and DICE-UNC/jargon-irods-ext#35.

**Comment by trel** [comment]
awaiting https://github.com/DICE-UNC/jargon-irods-ext/pull/35

**Comment by trel** [comment]
I think this is complete.

**Comment by JustinKyleJames** [comment]
This has been merged.  Closing.
