### ISSUE TITLE
PostgreSQL version compatability

### ISSUE THREAD

**Issue by kript** [irods-contrib/metalnx-web#344]
Hi folks,

it would be good to know what versions are compatible for PostgreSQL - our DBA's would like to upgrade our back end to 14. We're running 2.3.0 instances against 4.2.7 and 4.2.11, if that's any help, and I am interested in the metalNX back end in this issue.

cheers

John

**Comment by trel** [comment]
I tried to bump the sample docker-compose.yml from `postgres:11` to `postgres:14`, but it didn't come up cleanly.  

https://github.com/irods-contrib/metalnx-web#deploying-packaged-metalnx-via-docker-compose

So, there's a bit more investigation to do.

**Comment by trel** [comment]
#214 is now closed as complete - there is no more metalnx database.

closing this issue.
