### ISSUE TITLE
Issue with adding template from JSON

### ISSUE THREAD

**Issue by marchoeppner** [irods-contrib/metalnx-web#361]
Hi,

fairly new Metalnx user here, so this is possibly a trivial question/problem. 

I have a working iRODS installation on my test machine, bare metal. Everything seems to work ok there. 

I have then deployed Metalnx via Docker, which starts up and accesses iRODS just fine - as far as I can tell. 

Now, I would like to add complex metadata templates to my setup. One way would be to manually create and populate each schema via the Metalnx Template section. But at > 100 keys, this would simply not be feasible. 

Instead, I would like to upload complete schemas as pre-built JSONs. 

My issue(s):

1) Where is the JSON standard for templates defined, exactly?
2) When downloading a hand-build schema if 2 keys and trying to re-upload, I simply get an "internal error". 

`attrib:org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.emc.metalnx.services.interfaces.MetadataTemplateException: error parsing template from JSON
`

So I am guessing the formatting is wrong, which kind of circles back to issue 1. 

Any help would be greatly appreciated!

/M

**Comment by trel** [comment]
Hi @marchoeppner  - welcome!

I am not sure the metadata templates parts of Metalnx ever really worked as advertised.

We'll look at this quickly, but it may be that the templates parts of this codebase will be removed in the run-up to 3.0.0.

**Comment by marchoeppner** [comment]
Hi, 

just checking to see if there are any news on this. 

Removing the option to use templates to define metadata standards on the front-end seems a bit problematic, seeing that one of the key use cases for iRODS is data management. Most of our dm tasks happen from the command line, of course, but if there is a GUI, then I suppose that GUI should enforce a given metadata standard. Which isn't going to be "fun" to add by hand. 

All the best
M

**Comment by trel** [comment]
No news in Metalnx itself.

We have made some progress on metadata templates more broadly...
https://github.com/irods-contrib/irods_working_group_metadata_templates

As those server-side microservices and functions settle and get incorporated by the server, then all clients can take advantage of what they provide, including Metalnx.

**Comment by trel** [comment]
#214 has landed - closing this for now.   we'll work out how to get templates back into metalnx once the working group code has been incorporated into the server.
