### ISSUE TITLE
Question regarding theming

### ISSUE THREAD

**Issue by kalylian** [irods-contrib/metalnx-web#362]
Hi,

I'm trying to customize Metalnx with my own logo and I seem to be unabe to do so. I'm VERY new to Spring, so this might be a dumb question. I'm running Metalnx in a container.

To my understanding of this [deployment configuration help](https://github.com/irods-contrib/metalnx-web/blob/main/CONFIGURATION.md) and the [web assets infopage](https://github.com/irods-contrib/metalnx-web/blob/main/src/metalnx-web/src/main/resources/views/web-assets/README.md), I need to follow the example of [customMetalnxConfig.xml](https://github.com/irods-contrib/metalnx-web/blob/main/docker-test-framework/etc/irods-ext/customMetalnxConfig.xml) for theming. The recommended path for a new logo seems to be  `/opt/irods-ext/metalnx/images`.  So this is what I did:
  - mounted a directory with my `logo.svg` at the given path
  - copied the permissions for `logo.svg` from `webapps/metalnx/WEB-INF/classes/static/images/logo.svg` (root/root and 640) and verified  `logo.svg` was visible in the container
  - adapted my `MetalnxConfig.xml` by adding `file:/opt/irods-ext/metalnx/images` to the mapping for images (just like in `customMetalnxConfig.xml`) 
  - deleted all cached data in my browser

But I still see the Metalnx logo, not mine.  I must be missing something and I'd be grateful for pointers.

Thanks in advance

Kaly

**Comment by korydraughn** [comment]
Excellent!
