### ISSUE TITLE
Do not modify group list on user add

### ISSUE THREAD

**Issue by JustinKyleJames** [irods-contrib/metalnx-web#369]
When a user is added, do not provide the form to update the group list and do not make Jargon calls to update this list.

If the groups assigned to the user need updating, the user can be modified later.

This is so the `public` group is handled according to server policy.

**Comment by trel** [comment]
the bug is that the second call is updating the group list and affecting the defaults set by the server

**Comment by JustinKyleJames** [comment]
This work has been merged.  Closing this issue.
