### ISSUE TITLE
Remove synch jobs from Metalnx into a stand-alone agent

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#37]
Remove synch job code and put into an independent agent, so that when metalnx is horizontally scaled it doesn't clobber itself.

This is for things like user/group synch, we can use this for metadata attrib auto complete and other things so it's still generally useful!

**Comment by sgworth** [comment]
This is a good idea.  The sync job was used to avoid an independent agent.
In a commercial enterprise environment an independent agent will have to be
evaluated for security risk by corporate IT security personnel along with
external evaluation and likely will require encrypted connections with
Metalnx.  The sync job avoided the overhead for this at the time.

We had considered using Rabbit MQ for this at the time to stay compatible
with the Spring environment.

SW

**Comment by trel** [comment]
sync jobs are gone with #214 having landed.   closing.
