### ISSUE TITLE
Allow user add for PAM via interface

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#38]
User add screen currently requires setting a password, allow password to be blank to accommodate sites that use PAM

**Comment by sgworth** [comment]
Mike,
That is odd.  Before the original team ended their work we had PAM working
properly, not requiring you to establish a password but diverting to PAM
for authentication.  Please feel free to fix if it is broken now.

SW

**Comment by michael-conway** [comment]
Pam works just fine! It's to allow the use of non pam logins when pam is
enabled

**Comment by sgworth** [comment]
Understood.  Sorry I got confused.
SW
