### ISSUE TITLE
Wiki references old version of binary packages

### ISSUE THREAD

**Issue by raf64flo** [irods-contrib/metalnx-web#40]
Hi,
This [section](https://github.com/irods-contrib/metalnx-web/wiki/Getting-Started#download-binary-packages) references version 1.1.1-3 of MetaLNX while up-to-date version is 1.4.0.9

May you change these links so that one does not get older version?

Example: 
- https://bintray.com/metalnx/rpm/emc-metalnx-web#files/ or https://dl.bintray.com/metalnx/rpm/
- https://dl.bintray.com/metalnx/deb/pool/e/emc-metalnx-web/

The best should be to feed the Direct download link at the bottom of [RPM](https://bintray.com/metalnx/rpm/emc-metalnx-web) and [DEB](https://bintray.com/metalnx/deb/emc-metalnx-web) pages so that one can always get the latest package without you to maintain the wiki at each release.

**Comment by trel** [comment]
this is resolved - moving to Docker for deployment.
