### ISSUE TITLE
2.0.0 Release Activities

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#43]
- update readme
- release notes
- license information
- consortium information
- push to dockerhub
- deployment information (.war vs. docker)

**Comment by michael-conway** [comment]
hey @trel as we near release time I will cut a jargon 4.3.0.0 release so we can update the pom and not have snapshots in there. That's already passing all the tests. FWIW the 4.2 is the mainline stable jargon and the 4.3 is the more cutting edge one that has lots of facilities for api and web interfaces. Let's be sure to coordinate that!

**Comment by trel** [comment]
definitely

**Comment by michael-conway** [comment]
I think it's time to pull the trigger on this! Let's start looking at 2.0.1 and 2.1.0. 

I think 2.1.0 should introduce a redo of the collection listing (performance, saved queries pulled forward from cloud browser) as well as a new landing page with 'google' search option via ES, that's on our own roadmap.

**Comment by trel** [comment]
Things work - one more test, and should publish later today/tonight.
