### ISSUE TITLE
Enhance metadata template editing

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#44]
Enhance metadata template editing to move towards the current Consortium view of Metadata Templates. 

* Evolve the metadata template reference implementation to use the 'irods-ext' database structure, bring up the new templates as separate tables via new migrations with eventual draw-down of the previous structures.

* Enhance metadata template services and editing per the agreed template feature set for the first iteration.

**Comment by michael-conway** [comment]
see attached mockups for some design proposals
[DC-templateDesigns_04092018.pdf](https://github.com/irods-contrib/metalnx-web/files/2144981/DC-templateDesigns_04092018.pdf)

**Comment by trel** [comment]
closing - templates from https://github.com/irods-contrib/irods_working_group_metadata_templates will be merged into the server... and then all this will need to be reimagined.
