### ISSUE TITLE
Apply Metadata Template and present formatted metadata in 'home view'

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#45]
Apply a metadata template to a chosen file or collection, bringing up editing/validating forms. 

* Provide enhanced metadata view formatted into the collection and data object 'home page'

* Allow 'click to edit' for metadata views

* Hide template AVUs in raw avu view with option to view all. Click on edit of a raw avu associated with a template brings up the template edit form

The proposed first design focuses on metadata template editing in the home view versus the collection view.

**Comment by michael-conway** [comment]
linked to #44

**Comment by michael-conway** [comment]
camp until mdtemplate wg completes

**Comment by trel** [comment]
let's leave it open and close it once templates are integrated.    can bump it along until ready.

**Comment by trel** [comment]
closing - templates from https://github.com/irods-contrib/irods_working_group_metadata_templates will be merged into the server... and then all this will need to be reimagined.
