### ISSUE TITLE
Metalnx 2.0  src files must be updated with BSD 3-clause license

### ISSUE THREAD

**Issue by sgworth** [irods-contrib/metalnx-web#46]

**Comment by michael-conway** [comment]
what should this about box say?

<img width="921" alt="about" src="https://user-images.githubusercontent.com/1097261/42032046-49e054ee-7aa6-11e8-87d8-fc03a9f1c818.png">

**Comment by trel** [comment]
How's this?

```
Metalnx

Copyright (c) 2015-2017, Dell EMC
Copyright (c) 2018, University of North Carolina at Chapel Hill

Licensed under a BSD 3-Clause License

https://github.com/irods-contrib/metalnx-web
```

Can we update the `Metalnx Version` to include the git SHA?

**Comment by michael-conway** [comment]
sounds good Terrell I will change the verbiage in the about. Need to look at the fancy magik that can add the git SHA

**Comment by trel** [comment]
The result from `git describe --long` would be great.

**Comment by michael-conway** [comment]
ok sure just need to figure out how to automate...what mvn plugin etc

**Comment by michael-conway** [comment]
perhaps https://github.com/ktoso/maven-git-commit-id-plugin

**Comment by trel** [comment]
seems exactly what you want

**Comment by trel** [comment]
all files updated - merged.

close when the about box is updated.
