### ISSUE TITLE
User request for auto and semi-automated account creation from login page

### ISSUE THREAD

**Issue by sgworth** [irods-contrib/metalnx-web#51]
Multiple user requests to allow Metalnx to provide a "User Registration" capability where a new iRODS user can request account creation from the login page and have the account created automatically (no approval required) or after a simple approval from a designated iRODS admin.

**Comment by michael-conway** [comment]
kick the can...what would a user provisioning framework look like? E.g. does this assume standard auth? This seems less useful as we rely more on external authentication via pam, oauth, etc. Should provisioning be out-of-scope?

**Comment by trel** [comment]
I think this is out of scope for a client.

**Comment by trel** [comment]
closing.
