### ISSUE TITLE
expose shared links functionality

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#59]
related to https://github.com/irods-contrib/metalnx-web/issues/58 (favorites)

Shared links were put in place solely to solve the problem of someone giving permission to an object along a path that the receiving user cannot follow due to path permissions.  When given permission to an object the grantor could choose to have a "shared link" given automatically to that user.  The link on the shared link page could be used to jump to the collection (which they have access to) even though a higher level collection point would block them from following the collection tree. 

- shared link item in left menu
- shared link in permission setting tab

**Comment by michael-conway** [comment]
See #63

**Comment by michael-conway** [comment]
This maps to an NIEHS internal issue we identified to make shares work the way that they work in DE and Cloud Browser...via AVU tags. This would allow shares and favorites to work across iRODS federations and make the database footprint smaller.

**Comment by michael-conway** [comment]
PS Shared links are there but there is some error, let's clean that up before 2.0.0 release, even though shares might need to be reconsidered to be standard AVUs in later issues

**Comment by michael-conway** [comment]
testing shows all functions available...closing!
