### ISSUE TITLE
Problems with migrations and @Auditable

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#68]
Temporarily turn off hibernate @Audited annotations in entities to avoid potential migration problems. Revisit if @Auditable is a beneficial and desired behavior for the metalnx database.

**Comment by michael-conway** [comment]
kick this to 2.2.1 as it may be moot as we draw down the metalnx database

**Comment by trel** [comment]
#214 has removed the database - no more migrations.    closing.
