### ISSUE TITLE
update logo and URLs for generic release

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#73]
URL and logo at:
```
/emc-metalnx-web/login/authenticate/
```
<img width="813" alt="screen shot 2018-09-13 at 6 41 51 pm" src="https://user-images.githubusercontent.com/55238/45519801-be3c7780-b784-11e8-8db1-8a5ea397c699.png">

**Comment by michael-conway** [comment]
Prob config @trel . I'm switching to master and will spin it up, can help you look at it but it will be in the logs.

**Comment by trel** [comment]
I snuck a peak and saw lots of hard-coded URL prefixes... is that a config too?

**Comment by michael-conway** [comment]
for example?

**Comment by trel** [comment]
```
$ grep -rI "emc-metalnx-web" . | wc -l
265
```

Removing the URL everywhere is more work, but we definitely need to get a generic logo included in 2.0.0.

When you deploy, the URL shown to your users does not include EMC?  If so, how does that mechanism work?

**Comment by michael-conway** [comment]
it does show emc, that's the 'context'. In later enhancements we want to
make it a straight spring boot app and then the context can be removed and
it will just be host:port/

So that's not hard coded, that's actually the configured app context. In
the short term it can indeed be changed to something else in the web
app.xml.

**Comment by michael-conway** [comment]
Do we have a notion of what the actual default logo would be? If we can spin up a logo we can add it! Huh @trel ?

**Comment by trel** [comment]
I think if we just remove the DELL EMC part - chop it to only say metalnx - should be good to go for now.

**Comment by michael-conway** [comment]
Do you have folks that can do that? We're not graphics types

**Comment by trel** [comment]
yes, we can do the graphic.   can we change the URL structure to just be /metalnx-web/ ?

**Comment by michael-conway** [comment]
Yes, I'll make a sep issue

**Comment by michael-conway** [comment]
how about just 'metalnx'?

**Comment by sgworth** [comment]
Terrell's suggestion is good.  I recommend the final logo should the the
simple "iR" logo like in a tab header on the irods.org web site followed by
the work Metalnx.  I think it would be good to move the color mapping to
the iRODS white/green color scheme.

**Comment by trel** [comment]
just 'metalnx' is fine fine.

let's get it into the main irods repo namespace before branding it with the iR and colors.

**Comment by trel** [comment]
the renaming to 'metalnx' (#87) has landed.
