### ISSUE TITLE
allow navigation back to zone root via breadcrumbs

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#77]
We discovered a use case where an installation is not planning to use the traditional `/zonename/home/...` collection layout, and instead, planning to use project-based naming at the root of their zone (aka `/zonename/projectA/subcoll`.

The breadcrumbs should allow a clickable/navigable way to get to those top-level collections.

**Comment by michael-conway** [comment]
this actually was always there but behind the 'advanced view' button. I'll temporarily relax that and we can think about finer grained 'preferences'.

**Comment by trel** [comment]
oh?  how do I turn that 'on'/'off'?

**Comment by michael-conway** [comment]
you don't have to. It's now on by default to show it.

We can perhaps work on finer grained properties and settings later so that
sites can choose that behavior as they roll out the interface
