### ISSUE TITLE
Non-administrators directed to dashboard and given 403

### ISSUE THREAD

**Issue by jonlandrum** [irods-contrib/metalnx-web#83]
If a rodsuser has the login page bookmarked in their browser and clicks that link to navigate to Metalnx, they are presented with an authentication request and subsequently redirected to the Collections page upon successful login.

However, if they browse away from Metalnx or have their browser configured to not delete cookies, and then try to navigate to Metalnx with that bookmark, the login page redirects them to the Dashboard, at which time they are given a 403 error.

The proposed solution is either the login page should redirect only admins or groupadmins to the Dashboard, and rodsusers to Collections, or the Dashboard page should redirect rodsusers to the Collections page instead of displaying a 403 error page.

**Comment by michael-conway** [comment]
Thanks for the report. This would be a bug. The navigation is admittedly a little bit funny because it tries to mix 'REST' style interactions with Thymeleaf interactions, and this does need to be cleaned up! I'll take a look at how to smooth this out in the meantime.

**Comment by michael-conway** [comment]
...we're reworking the dashboard code (per commit #84) and I'll retest this before we push the new version.

**Comment by trel** [comment]
Dashboard is off by default now - closing this - we'll open another if there is a new bug.
