### ISSUE TITLE
dashboard slow to load

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#84]
With a couple hundred million files in a Zone, the dashboard is very slow to load  - initial page rendering takes 3-5 minutes.

Should asynchronously render the page elements, and cache the results for the next time.

**Comment by michael-conway** [comment]
Solution here is to temporarily remove the dashboard (there are already concepts for a new 'home' page elsewhere. Proposed is to hide it with a metalnx.properties flag by default, but have it available if it's really wanted.

**Comment by michael-conway** [comment]
Dashboard needs a refresh to go along with some consensus/discussion on how to proceed with the monitoring agent. In this the proposal is to make stats gathering an asynch process (perhaps part of the monitoring agent service)  to improve load performance.
