### ISSUE TITLE
refresh page should login and return to same location

### ISSUE THREAD

**Issue by trel** [irods-contrib/metalnx-web#85]
After a while, a refresh or interaction with a page that has timed-out, the user is taken to the authentication flow again, but then taken to their home directory or the dashboard (for admins).

The user should instead be taken to the location they were originally trying to get to before having to re-authenticate.

**Comment by michael-conway** [comment]
This is going to take more work, there are some intrinsic issues with how metalnx mixes rest based and thymeleaf interaction. Currently, the 'last url' is stored in HTTP session, which of course doesn't exist on session timeout...

This is too much try try to do in a short span, let's move this out to a later issue as we continue to factor things out.

**Comment by trel** [comment]
okay - sounds good

**Comment by michael-conway** [comment]
This has been cleaned up and is reflected in 2.0.0
