### ISSUE TITLE
change web context

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#87]
change from emc-metalnx-web to either metalnx-web or metalnx or something else.

What is the consensus on the default context?

**Comment by trel** [comment]
just 'metalnx'.   the 'web' is implicit.

**Comment by michael-conway** [comment]
ok will do that (I think it's just a mass change of sorts).

**Comment by sgworth** [comment]
The original thinking around the words emc-metalnx-web was to allow for the
concept of a web version, mobile version,  possible OS dependent versions,
whatever.  The emc was to provide clarity if we had ended up contributing
this to a 3rd party marketplace.  I should think given the current state of
things shortening it to just metalnx would be fine and would be my
recommendation.  Keep it simple.

SW

**Comment by michael-conway** [comment]
good deal it's now just 'metalnx' need to do some testing to make sure no side-effects before committing, I like that too.
