### ISSUE TITLE
Add mapping to friendly names for auth types

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#88]
Add a mapping in metalnx.props for auth methods so that users are not confronted with PAM and Standard, etc.

Instead allow override so PAM can be something like NIEHS Account in our case.

**Comment by michael-conway** [comment]
Updated. Now it looks like this...

![image](https://user-images.githubusercontent.com/1097261/53425287-b713c980-39b2-11e9-85f4-d0c1b7daeaae.png)

This is set in metalnx.properties like this example...

```
#############################
# misc ui configuration niceties
#############################
# allow translation of iRODS auth types to user friendly names in login
# in the form irodstype:displaytype|
metalnx.authtype.mappings=PAM:NIH Login|STANDARD:iRODS Auth
```

**Comment by sgworth** [comment]
Beautiful!  Thxs!
SW
