### ISSUE TITLE
Trying out Metalnx 2.0 with Docker

### ISSUE THREAD

**Issue by acnewton** [irods-contrib/metalnx-web#92]
I want to try out Metalanx 2.0, however I am not able to install it correctly.

I have tried the rough description in: https://groups.google.com/forum/#!topic/iROD-Chat/xOOWcbkiDOg. But that doesn't work. I get a "500 Internal server error" when I go to http://<ip-address>:8080/metalnx/login/ (also tried ../emc-metalnx-web/login/ ).

I have also tried following the 'Getting started' docs:
https://github.com/irods-contrib/metalnx-web/blob/master/docs/Getting-Started.md

Ideally I would like to test it out with Docker but couldn't get it to work by doing either:
1) (https://github.com/irods-contrib/metalnx-web/blob/master/docs/Docker.md)
```
docker run -d \
-p 8080:8080 \
-e IRODS_HOST="<IRODS_HOST_NAME>" \
-e IRODS_PORT=<IRODS_PORT> \
-e IRODS_ZONE="<IRODS_ZONE_NAME>" \
-e IRODS_USER="<IRODS_ADMIN_USERNAME>" \
-e IRODS_PASS="<IRODS_ADMIN_PASSWORD>" \
diceunc/metalnx:latest
```
2) (as in https://github.com/irods-contrib/metalnx-web/blob/master/packaging/docker/Dockerfile)
```
docker run -d --rm -p 8080:8080 -v /etc/irods-ext:/etc/irods-ext  -v /home/mcc/webdavcert:/tmp/cert --add-host irods420.irodslocal:172.16.250.101 diceunc/metalnx:latest
```
I have a simple iRODS instance I want to connect to without SSL. I have set CS_NEG_REFUSE in the core.re. 

How would I be able to run the latest docker image?

**Comment by michael-conway** [comment]
There are still some vestage docs we are cleaning out as we work on the 2.0 release. I think this is what is causing your issue. The env variable approach is not supported. 

The way this works with docker is that the docker image expects an /etc/irods-ext/metalnx.properties and metalnxConfig.xml file to be mounted. All the configuration is in the metalnx.properties.  

Check out the /etc directory in this github repo. This gives placeholders for the various settings. As long as those two files are visible in to the docker image under /etc/irods-ext it should be happy.

Here's an example docker run I use for development...


```
docker run -i -t \
-p 8080:8080 \
-v /Users/conwaymc/Documents/docker/ml_dfc/etc/irods-ext:/etc/irods-ext \
xxx/metalnx:2.0.0

```


So along these lines (NB we just met over at RENCI to work on this, so there will be detailed instructions with the 2.0.0 Release!)

* copy the /etc/irods-ext directory to a location on the server.
* modify the metalnx.properties file according to local settings
* mount etc/irods-ext in the docker container

The only other thing that's needed (and we're still working on simplifying this) is the migration of the database that metalnx uses. This is covered in the readme in the metalnx-tools subproject. I'm happy to walk you through this via DM mike.conway@nih.gov

Smoothing this out and documenting it is the part that's holding up the 2.0.0 release, but once the database is set up it should go smoothly.

**Comment by acnewton** [comment]
Thanks for the reply. I tried to make it work with your command, but I am missing something somewhere unfortunately and I don't understand what. 

I will wait for the detailed instructions in the upcoming release :). Looking forward to it.

**Comment by michael-conway** [comment]
Sure thing, if you want to share some logs etc I can help you get started either sooner as it is released. This is down to final details and a few small issues
