### ISSUE TITLE
Metadata search only returns data object

### ISSUE THREAD

**Issue by beheerderdag** [irods-contrib/metalnx-web#98]
I have one iRODS server but two different metalnx versions running --  the current version and the pre-release (2.0.0). In the pre-release metadata search only returns data object, not collection. 

Here's my collection and data: 
```
# imeta ls -C Folder12345
AVUs defined for collection Folder12345:
attribute: Color
value: Green
units: 
----
attribute: Region
value: South
units: 

# imeta ls -d Folder12345/myFile.data
AVUs defined for dataObj Folder12345/myFile.data:
attribute: Region
value: South
units: 
```

Screenshots: 
Search only returns object: 

<img width="958" alt="metadata-object-only" src="https://user-images.githubusercontent.com/26715026/54436521-fbcd8d80-4732-11e9-9ef4-65a0b66150c8.png">

In the current version search returns both collection and object 

<img width="1134" alt="metalnx-metadata-object-coll" src="https://user-images.githubusercontent.com/26715026/54436523-fc662400-4732-11e9-8c92-67bedcc59eec.png">

**Comment by michael-conway** [comment]
OK we may need to add a radio button so that colls can be returned, as there's lots of collection level avu use cases!

**Comment by michael-conway** [comment]
PS this probably was me and something to clean up, we did a fix to make the paging work for big search result sets, it might have introduced a bug.

**Comment by michael-conway** [comment]
replicated in unit test....

**Comment by michael-conway** [comment]
![image](https://user-images.githubusercontent.com/1097261/55092002-2cdd8480-5088-11e9-9fd9-00550b3ebbf0.png)


Unit test and functional test appear to show success, will commit for retest

**Comment by michael-conway** [comment]
original case tested and verified..will close

![image](https://user-images.githubusercontent.com/1097261/55099428-0888a480-5096-11e9-80e1-0642bd321288.png)
