### ISSUE TITLE
unselecting shared link in permissions view does not remove shared link

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#99]
unselecting the shared link checkbox in permissions view should remove the shared link

**Comment by trel** [comment]
@JustinKyleJames is this no longer relevant since #214 has landed?

**Comment by JustinKyleJames** [comment]
> @JustinKyleJames is this no longer relevant since #214 has landed?

This is no longer applicable.

**Comment by korydraughn** [comment]
Because shared links have been removed, correct?

**Comment by trel** [comment]
Got it.   Thanks.   Closing.
